language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: i586-mingw32msvc-gcc

install:
  - export CC=i586-mingw32msvc-gcc
  - export CXX=i586-mingw32msvc-g++

script:
  - test -d bin || mkdir bin
  - cd bin
  - cmake ..
  - cmake --build .

after_script:
  - ./travis-test
