language: cpp

compiler:
  - gcc

script:
  - test -d bin || mkdir bin
  - cd bin
  - cmake ..
  - cmake --build .
  - cp ../mytest.sh .

after_script:
  - pwd
  - ls -al
  - ctest -V .
#  - ./travis-test
