language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - env: CC=i586-mingw32msvc-gcc CXX=i586-mingw32msvc-g++

script:
  - test -d bin || mkdir bin
  - cd bin
  - cmake ..
  - cmake --build .

after_script:
  - ./travis-test
