language: cpp

compiler:
  - gcc
  - clang

matrix:
  include:
    - compiler: i586-mingw32msvc-gcc

script:
  - test -d bin || mkdir bin
  - cd bin
  - cmake ..
  - cmake --build .

after_script:
  - ./travis-test
